name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ganti dengan branch utama Anda jika bukan `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Pastikan versi sesuai kebutuhan Anda

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build aplikasi
    - name: Build the project
      run: npm run build

    # 5. Deploy ke GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Folder hasil build
