name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ganti dengan branch utama Anda jika bukan `main`

jobs:
  build-and-deploy:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest] # Tes di ubuntu-22.04 dan versi terbaru
    runs-on: ${{ matrix.os }}

    steps:
    # 1. Checkout kode
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Pastikan versi Node.js sesuai kebutuhan proyek

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build aplikasi
    - name: Build the project
      run: npm run build

    # 5. Deploy ke GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Ganti dengan folder hasil build Anda
